name: albrain_client
description: Albrain Books — client app (Firebase + Google Sign-In).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  albrain_core:
    path: ../../packages/albrain_core

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
