// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ro0LxINiVt5jY4Yq6340CuSAyRcMmos',
    appId: '1:431084553743:android:9a9fd16591b9cfd18e857a',
    messagingSenderId: '431084553743',
    projectId: 'pro-2d9f0',
    storageBucket: 'pro-2d9f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweJYU6vB6Mf4-zmWhFg5MDNIfPCZOHBs',
    appId: '1:431084553743:ios:9f1babd3c1f3f2568e857a',
    messagingSenderId: '431084553743',
    projectId: 'pro-2d9f0',
    storageBucket: 'pro-2d9f0.firebasestorage.app',
    androidClientId: '431084553743-0pfd8jjjdsqcflbsb3a87v6kdrv36boa.apps.googleusercontent.com',
    iosClientId: '431084553743-d1lkje4slsb0h4k2dfm198ateoi088kv.apps.googleusercontent.com',
    iosBundleId: 'com.example.albrainClient',
  );
}
